name = input("Enter a name of a person: ")
name2 = input("Enter a another name of a person: ")
virus_name = input("Enter a name of a imaginary thing: ")
antivirus_name = input("Enter a name of another imaginary thing: ")
animal_name = input("Enter a name of a animal: ")
mutated_animal_name = input("Enter a name of a imaginary animal: ")
infection_days = input("Enter a small number of days: ")
zoo_name = input("Enter a name of a place: ")
feeling = input("Enter a feeling: ")


print(f"There was once a mad scientist. His name was {name}. He was experimenting a mad virus. he named it {virus_name} virus.")
print(f"It was capable of mutating {animal_name} completely in {infection_days} days. He decided to use it,")
print(f"So, he went to the {zoo_name} zoo. There, he secretly mixed it with the food of the {animal_name}." )
print(f"After that, he went home and turned on his tv to see thee chaos unfold. And, it was total chaos.")
print(f"At first, it was just the {animal_name} going mad. It broke out the zoo, and thus, the spreading began.")
print(f"After some time, the good scientist {name2} developed a cure. It was called {antivirus_name} antivirus.")
print(f"It successfully prevented the spreading of the virus. But the animals already mutated were left out and nothing could be done about them.")
print(f"So, the animals mutated were given a new name. They were called {mutated_animal_name}.")
print(f"{name} felt very {feeling}")